### ISSUE TITLE
请问下支付方法的那个mContext是什么变量

### ISSUE THREAD

**Issue by YuanSuDi** [Javen205/JPay#6]
我试了当前Activity的对象，报错了

**Comment by Javen205** [comment]
是Activity  报什么错误请截图

**Comment by tong19950305** [comment]
![tim 20171223082016](https://user-images.githubusercontent.com/21289744/34315427-5a01186a-e7ba-11e7-850f-b2f1efb85c32.png)
![tim 20171223081938](https://user-images.githubusercontent.com/21289744/34315433-64cb173c-e7ba-11e7-8cb8-57884e6f80ee.png)

**Comment by Javen205** [comment]
你为啥要`new MainActivity()`  你直接在`MainActivity的OnCreate()`方法中获取就可以了呀。
或者使用直接使用`MainActivity.this`

**Comment by YuanSuDi** [comment]
好了，暂时不报错了，谢谢
